### PR TITLE
[PROPOSAL] docs: add initial `md-book` 

### PR DESCRIPTION
**Pull request by chazkiker2**
## Description

This PR offers a proposal for how we could use `mdBook` as a tool for higher-level documentation, consolidation of information, and open vision tracking.

- See relevant discussion: #22 
- See [`rust-lang/wg-async-foundations`](https://rust-lang.github.io/wg-async-foundations/welcome.html) as an example of what this could look like down the road. 

As we continue to develop the protocol, we could consolidate information within the `md-book`. It would act primarily as a referential resource for contributors looking to learn more about the project and get involved. Not a bad way to openly document the project vision.

## What was done? 

- [x] create `md-book` with [`mdBook::init`](https://rust-lang.github.io/mdBook/cli/init.html)
- [x] include Agile personas in the book to provide those characters publicly. Now, anyone could reference the user stories in the Pivotal Tracker and make more sense of things

### CODE REVIEW

**Comment by shelbyd** [comment]
Thanks for starting this! I don't have much time to actively contribute authoring to this ATM, so we may want to start with the barebones (what you have now, or can figure out from what we've put out). I can spare the time to review this PR if you want to add things you're not as sure about. I can also answer questions here or in other discussions.

**Comment by chazkiker2** [comment]
@shelbyd No worries RE: time to contribute authoring! 

I think the bare-bones approach is great — and the nice thing about these books is you can leave `TODO`s all over the place. But it at least keeps it around for someone who wants to explore, and then it's easier to add to over time.  

I might go through and just delete some unnecessary bulk here, add the `CONTRIBUTING.md` file with some TODOs in there.

And then maybe we can leave it like that for the moment and build as we go. 

Thoughts?

**Comment by chazkiker2** [comment]
@shelbyd, would you be willing to give this a review?

- I've added a simple contributing page with some additional resources and removed some of the previously existing excess bulk. 
- I think it's in a pretty decent place for a bare-bones start :smile:. It will at least provide a place to start for potentially interested people who stumble along.

Sorry that I didn't circle back to this faster—I've been sucked into some rust-lang stuff.

**Comment by chazkiker2** [comment]
Also, I believe mdbook makes it pretty easy to deploy to github-pages. I'll just toss these resources in this comment so that it's around, but I figure since you've already been wrestling with CI at some level, you may not be motivated to add this to the agenda. 

- [mdbook docs: CI](https://rust-lang.github.io/mdBook/continuous-integration.html)
- [CircleCI Blog: deploy docs to GH pages with CI](https://circleci.com/blog/deploying-documentation-to-github-pages-with-continuous-integration/)

I think the job could be as simple as something like this:

*(Note: I have not tried to run this, and I have zero experience with CirlceCI... but based on what's in your `config.yml,` this was my first attempt/best guess)*

```yml
jobs:
  # ... snip ...
  build-md-book:
    docker:
      - image: circleci/rust
    steps:
      - *install_deps
      - *setup_rust
      - *version_info
      - checkout
      - run:
        name: Install and Build
        command: |
          cargo install mdbook
          cd md-book && mdbook build
```

**Comment by shelbyd** [comment]
Sorry that this isn't a high priority right now. Our mainnet release is
next Tues, Oct 19. And otherwise, things are improving. Hope things are
good with you too.

**Pull request closed without merging**
